# Generated by Django 3.1.2 on 2021-06-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
