# Generated by Django 3.1.2 on 2021-06-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpapp', '0002_doubt_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
