# Generated by Django 3.1.2 on 2021-06-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpapp', '0003_auto_20210625_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='doubt',
        ),
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dpapp.answer'),
        ),
    ]
