# Generated by Django 3.2.5 on 2021-07-13 03:35

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('dpapp', '0006_notification_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubt',
            name='tags',
        ),
        migrations.AddField(
            model_name='doubt',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
